server:
  port: 8080
  servlet:
    context-path: /demo


management:
  endpoints:
    web:
      exposure:
        include: "*"
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin # XXL-JOB Admin 的地址
    executor:
      appname: my-springboot-job      # 执行器名称
      address:                       # 执行器的地址 (可为空，由 XXL-JOB Admin 自动发现)
      ip:                            # 可选：执行器的绑定 IP
      port: 9999                     # 执行器的端口，默认为随机端口
      logpath: /data/applogs/xxl-job # 执行器的日志存储路径
      logretentiondays: 30           # 日志保存天数
